### ISSUE TITLE
Can you add compatible ruby and gem version for this code

### ISSUE THREAD

**Issue by dhajoshi** [lateralblast/druid#1]

**Comment by richardatlateralblast** [comment]
From what I remember, Dell has changed the URLs, so this script no longer works. I've updated the README. I'm not sure when I'll get a chance to update it.

**Comment by dhajoshi** [comment]
> From what I remember, Dell has changed the URLs, so this script no longer works. I've updated the README. I'm not sure when I'll get a chance to update it.

Ups thats sad, this is the only code i found, let me know if you are aware of something similar.

**Comment by richardatlateralblast** [comment]
Updated script to use Selenium Firefox Webdriver and update script to process updated website.
Also updated code to automatically install required modules.
